services:
  fastapi:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: fastapi
      POSTGRES_USER: postgres
      POSTGRES_DB: hw02
